version: "3"
services:
  db:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=videogamer
      - POSTGRES_PASSWORD=pwned-by-headshot-1337
      - POSTGRES_DB=videogames
    ports:
      - 5432:5432
    volumes:
      - ./.pgdatabase:/var/lib/postgresql/data
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
